#!/usr/bin/env python3
"""Compose a flattened, import-expanded Salmon Domain Ontology TTL artifact.

This script resolves local `owl:imports` recursively from the canonical source
TTL and writes a single merged TTL file suitable for low-friction consumption.
The generated output intentionally strips `owl:imports` triples so it behaves like a
stable "master" read-only artifact.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict

from rdflib import Graph, URIRef
from rdflib.namespace import OWL, RDF

ROOT = Path(__file__).resolve().parents[1]
ONTOLOGY_ROOT = ROOT / "ontology"
SOURCE_DEFAULT = Path("ontology") / "salmon-domain-ontology.ttl"
FLAT_DEFAULT = Path("salmon-domain-ontology.ttl")


def discover_local_ontology_index() -> Dict[str, Path]:
    """Build mapping of ontology IRI -> local file path for local module imports."""
    index: Dict[str, Path] = {}
    for path in sorted(ONTOLOGY_ROOT.rglob("*.ttl")):
        graph = Graph()
        graph.parse(path, format="turtle")
        ontology_iri = graph.value(predicate=RDF.type, object=OWL.Ontology)
        if isinstance(ontology_iri, URIRef):
            index[str(ontology_iri)] = path
    return index


def collect_import_closure(source_path: Path, index: Dict[str, Path]) -> Graph:
    graph = Graph()
    visited_paths = set()

    def visit(path: Path) -> None:
        if path in visited_paths:
            return
        if not path.exists():
            raise FileNotFoundError(f"Local ontology file not found: {path}")

        local_graph = Graph()
        local_graph.parse(path, format="turtle")
        for triple in local_graph:
            graph.add(triple)
        visited_paths.add(path)

        # Recurse deterministically through local imports.
        import_uris = sorted(
            (obj for obj in local_graph.objects(None, OWL.imports) if isinstance(obj, URIRef)),
            key=str,
        )
        for import_uri in import_uris:
            imported_path = index.get(str(import_uri))
            if imported_path is None:
                # Non-local imports are intentionally left as-is; consumers can resolve
                # those via standard ontology resolution if needed.
                continue
            if imported_path == path:
                continue
            visit(imported_path)

    visit(source_path)

    # Flattened file should be import-free and single-file consumable.
    for s, _, o in list(graph.triples((None, OWL.imports, None))):
        graph.remove((s, OWL.imports, o))

    return graph


def build_flat_ttl(*, source_path: Path, output_path: Path) -> None:
    if not source_path.exists():
        raise FileNotFoundError(f"Source ontology not found: {source_path}")

    index = discover_local_ontology_index()
    flat_graph = collect_import_closure(source_path=source_path, index=index)

    serialized = flat_graph.serialize(format="turtle", sort_keys=True)
    if isinstance(serialized, bytes):
        serialized = serialized.decode("utf-8")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "# Auto-generated flattened TTL (read-only source artifact)\n"
        "# Generated by: scripts/build_flat_smn_ttl.py\n"
        f"# Source: {source_path}\n"
        "# DO NOT edit manually. Rebuild with `make compose-flat-ttl`.\n"
        "\n"
        + str(serialized),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a flattened local master TTL file.")
    parser.add_argument(
        "--source",
        type=Path,
        default=SOURCE_DEFAULT,
        help="Source ontology entrypoint (default: ontology/salmon-domain-ontology.ttl)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=FLAT_DEFAULT,
        help="Output flattened TTL file (default: salmon-domain-ontology.ttl)",
    )

    args = parser.parse_args()
    try:
        build_flat_ttl(source_path=args.source, output_path=args.output)
    except Exception as exc:  # broad by design: CLI user gets one clear error path.
        print(f"❌ failed to build flat TTL: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
