#!/usr/bin/env python3
"""Build a WIDOCO input file with only the root ontology declaration retained."""

from __future__ import annotations

import argparse
from pathlib import Path

from rdflib import Graph, URIRef
from rdflib.namespace import OWL, RDF


ROOT = Path(__file__).resolve().parents[1]
INPUT_DEFAULT = ROOT / "salmon-domain-ontology.ttl"
OUTPUT_DEFAULT = ROOT / "release" / "tmp" / "widoco-input.ttl"
ROOT_ONTOLOGY = URIRef("https://w3id.org/smn")


def build_widoco_input(input_path: Path, output_path: Path) -> None:
    input_path = input_path.resolve()
    output_path = output_path.resolve()
    graph = Graph()
    graph.parse(input_path, format="turtle")

    ontology_subjects = {
        subject for subject in graph.subjects(RDF.type, OWL.Ontology) if isinstance(subject, URIRef)
    }
    for subject in ontology_subjects:
        if subject == ROOT_ONTOLOGY:
            continue
        for triple in list(graph.triples((subject, None, None))):
            graph.remove(triple)

    serialized = graph.serialize(format="turtle", sort_keys=True)
    if isinstance(serialized, bytes):
        serialized = serialized.decode("utf-8")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "# Auto-generated WIDOCO input (read-only source artifact)\n"
        "# Generated by: scripts/build_widoco_input.py\n"
        f"# Source: {input_path.relative_to(ROOT).as_posix()}\n"
        "# DO NOT edit manually. Rebuild with `make docs-widoco`.\n\n"
        + serialized,
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=INPUT_DEFAULT)
    parser.add_argument("--output", type=Path, default=OUTPUT_DEFAULT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    build_widoco_input(args.input, args.output)
    print(f"Wrote WIDOCO input: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
